### ISSUE TITLE
JC 3.2 lua find function issue

### ISSUE THREAD

**Issue by RealAntithesis** [SilverIce/JContainers#40] opened 2015-01-27 15:38 UTC
Hi, I think there may be an issue with the jc.find function in JContainers 3.2. When adding the JC 3.2 files to AH Hotkeys, the lua find function started giving incorrect results (finding JMap fields in an array). Doing a test script indicated that the JC 3.2 function may be counting the first element of an array as 1 instead of zero.

e.g. 
```lua
function DoTest()
	int testMap1 = JMap.object()
	JMap.setInt(testMap1, "itemSlot", 42)
	int testMap2 = JMap.object()
	JMap.setInt(testMap2, "itemSlot", 33)
	int testMap3 = JMap.object()
	JMap.setInt(testMap3, "itemSlot", 56)
	int testArray = JArray.object()
	JArray.addObj(testArray, testMap1)
	JArray.addObj(testArray, testMap2)
	JArray.addObj(testArray, testMap3)
	int itemSlotToFind = 42 ; lookup this value in the evalLuaInt
	int actualIndex = 0 ; this is the actual array item (note: starts from 0)
	int foundIndex = JValue.evalLuaInt(testArray, "return jc.find(jobject, function(x) return x.itemSlot == " + itemSlotToFind + " end)")
	DebugMessage("DoTest(): evalLuaInt returned foundIndex of " + foundIndex + "; actualIndex is " + actualIndex)
endFunction
```
if itemSlotToFind is 42, evalLuaInt returns 1, not 0
if itemSlotToFind is 33, evalLuaInt returns 2, not 1
if itemSlotToFind is 56, evalLuaInt returns 3, not 2

Could you have a look? I'm assuming that JArray indices should still start from zero? Thanks :)

**Comment by SilverIce** [comment] 2015-01-27 20:29
Mm I think I completely forgot about that part and it causes compatibility issue now..
Yes, containers are one-base in Papyrus.
The issue is that in Lua environment indices have to start with 1 (to guarantee that that `for x in yyy-object do` iteration will work properly). That's the way the rest of Lua environment works and I have to preserve consistence. Otherwise, if i'll leave containers in lua zero-based, there will be much more confusion as everything is one-based

**Comment by SilverIce** [comment] 2015-01-27 21:34
You could rewrite `findFrom`, it looks much simpler now...
```lua
function AH_Hotkeys.findFrom2(collection, predicate, startIndex)
  for i = startIndex + 1, #collection do
    if predicate(collection[i]) then return i - 1 end
  end
  return -1
end
```

`jc.find` looks enough simple and it was supposed to replace collection operator functions, thus it can be turned into zero-based..

**Comment by RealAntithesis** [comment] 2015-01-27 23:42
Hmmm, I'm not sure JC 3.2 is finding my init.lua file. Whenever I try to call a function from this file, I get the following error:
```
Lua error: [string "local jobject = ... ;return AHHotkeys.findInd..."]:1: attempt to index global 'AHHotkeys' (a nil value)
Lua error: stack traceback:
	[C]: in function '__index'
	[string "local jobject = ... ;return AHHotkeys.findInd..."]:1: in function 'func'
	...ners 3.2/SKSE/Plugins/JCData/InternalLuaScripts/init.lua:204: in function <...ners 3.2/SKSE/Plugins/JCData/InternalLuaScripts/init.lua:201>
```
The folder structure is:
Mod Top Level\SKSE\Plugins\JCData\lua\AHHotkeys\init.lua
The init.lua file contains:
```
local AHHotkeys = {}

local jc = jrequire "jc"

function AHHotkeys.findIndex(collection, predicate, startIndex)
  for i = startIndex + 1, #collection do
    if predicate(collection[i]) then return i - 1 end
  end
  return -1
end

function AHHotkeys.findValue(collection, predicate, startIndex)
  for i = startIndex + 1, #collection do
    if predicate(collection[i]) then return collection[i] end
  end
  return nil
end

-- ...others

return AHHotkeys
```
Thanks

**Comment by SilverIce** [comment] 2015-01-28 09:13
@RealAntithesis, that's odd. In my test your  `AHHotkeys.testFunction` divides by 2, e.g. file can be loaded

**Comment by RealAntithesis** [comment] 2015-01-28 11:01
Yeah, I changed to AHHotkeys. to see if that made a difference, but it didn't. I've changed it all back to AH_Hotkeys (folder name, local AH_Hotkeys = {}, AH_Hotkeys.findIndex etc), but the same error happens. The same error happens with the testFunction. I'm probably doing something fundamentally wrong.

**Comment by SilverIce** [comment] 2015-01-28 11:45
Can you install JC and your mod directly into the Data folder? That could be even MO issue

**Comment by RealAntithesis** [comment] 2015-01-28 15:20
Thanks. It's something to do with MO. It's working now installing all the files directly into the Data folder. I'll investigate further.

**Comment by SilverIce** [comment] 2015-01-28 22:03
Yeah that was virtualization issue. The good news is that there is very simple fix, MO dev just didn't virtualized a function I use, MO, I suppose, will be fixed too

**Comment by RealAntithesis** [comment] 2015-01-29 07:55
Well, for now, I think I can just use the jc.find function and just subtract 1 from the found index results, since that function seemed to work for some odd reason.

**Comment by SilverIce** [comment] 2015-01-29 15:48
@RealAntithesis, or maybe it would be better to just duplicate `jc.find` functionality in AHHotkeys domain, to not subtract eveywhere..

**Comment by RealAntithesis** [comment] 2015-01-30 02:00
Well, I was assuming that it wouldn't even see that function since not even the test function was working for me.

**Comment by SilverIce** [comment] 2015-01-30 11:47
I'm about to release 3.2.1 can you test it? https://github.com/SilverIce/JContainers/releases/tag/v3.2.1

**Comment by RealAntithesis** [comment] 2015-01-30 22:51
Sure - as soon as I come back from holiday... in 2 weeks. Would this resolve the issue with mod lua files?

- Anthony

**Comment by RealAntithesis** [comment] 2015-01-30 22:54
Just saw the description of the update. I'll test out when I get back to my machine.

- Anthony

**Comment by SilverIce** [comment] 2015-02-01 13:55
Ah ok, have good holidays :+1:

**Comment by SilverIce** [comment] 2015-02-11 01:27
Well, will as close as the issue was turned into feature..

**Closed by SilverIce** 2015-02-11 01:27 UTC
Labels: bug
